#!/usr/bin/env python3
"""
Aureum Transpiler - Frontend to Backend
Reads .aur code, generates AST with Lark and transpiles to optimized Rust.

FOCUS: Maximum performance and memory efficiency with BitNet b1.58 and Matryoshka

Author: Luiz Antônio De Lima Mendonça
Location: Resende, RJ, Brazil
Instagram: @luizinvict
Date: 2026-03-25
"""

import sys
from pathlib import Path
from lark import Lark, Tree, Token
from lark.indenter import Indenter
from typing import Dict, List, Optional, Tuple


class AureumIndenter(Indenter):
    """Python-style indenter for Aureum"""
    NL_type = '_NL'
    OPEN_PAREN_types = []
    CLOSE_PAREN_types = []
    INDENT_type = '_INDENT'
    DEDENT_type = '_DEDENT'
    tab_len = 4


class AureumTranspiler:
    """Aureum → Rust transpiler with BitNet b1.58 and Matryoshka support"""
    
    def __init__(self, grammar_path: str):
        with open(grammar_path, 'r', encoding='utf-8') as f:
            grammar = f.read()
        self.parser = Lark(
            grammar, 
            parser='lalr', 
            start='start',
            postlex=AureumIndenter()
        )
        self.variables: Dict[str, str] = {}  # name → Rust type
        self.rust_code: List[str] = []
    
    def compile(self, source_code: str) -> str:
        """Compiles Aureum code to Rust"""
        tree = self.parser.parse(source_code)
        
        self.rust_code = [
            "// Code automatically generated by the Aureum Transpiler",
            "// OPTIMIZED: BitNet b1.58 (zero FP multiplications) + Matryoshka",
            "// AI-Native Standard Library: classify, detect, embed, summarize, similarity, topk",
            "use aureum_kernel::{pack_ternary, bitnet_infer};",
            "use aureum_kernel::stdlib as aureum_stdlib;",
            ""
        ]
        self._visit(tree)
        return "\n".join(self.rust_code)
    
    def _visit(self, node):
        """Visitor pattern to traverse the AST"""
        if isinstance(node, Tree):
            method_name = f"_visit_{node.data}"
            if hasattr(self, method_name):
                return getattr(self, method_name)(node)
            else:
                # Default recursive visit
                for child in node.children:
                    self._visit(child)
        return None
    
    def _visit_func_def(self, node: Tree):
        """Generates Rust function from 'def name():'"""
        func_name = node.children[0].value
        self.rust_code.append(f"\npub fn {func_name}() {{")
        
        # Process function body
        for child in node.children[1:]:
            self._visit(child)
        
        self.rust_code.append("}")
    
    def _visit_assignment(self, node: Tree):
        """Processes assignments: name = expr"""
        var_name = node.children[0]
        if isinstance(var_name, Token):
            var_name = var_name.value
        
        expr = node.children[1]
        
        # Detecta tipo da expressão
        if isinstance(expr, Tree):
            # Verifica se é tensor_expr diretamente
            if expr.data == 'tensor_expr':
                rust_type, rust_init = self._process_tensor(expr)
                self.variables[var_name] = rust_type
                self.rust_code.append(f"    let mut {var_name}: {rust_type} = {rust_init};")
                return
            
            # Verifica se é uma expressão que contém tensor_expr
            if expr.data == 'expr':
                inner = expr.children[0]
                if isinstance(inner, Tree):
                    if inner.data == 'tensor_expr':
                        rust_type, rust_init = self._process_tensor(inner)
                        self.variables[var_name] = rust_type
                        self.rust_code.append(f"    let mut {var_name}: {rust_type} = {rust_init};")
                        return
                    elif inner.data == 'mul':
                        # Verifica se é inferência BitNet (tem slice_expr)
                        if self._is_bitnet_inference(inner):
                            self._process_bitnet_inference(var_name, inner)
                            return
            
            # Verifica se é multiplicação BitNet
            if expr.data == 'mul':
                if self._is_bitnet_inference(expr):
                    self._process_bitnet_inference(var_name, expr)
                    return
        
        # Expressão genérica - processa normalmente
        rust_expr = self._process_expr(expr)
        self.rust_code.append(f"    let {var_name} = {rust_expr};")
    
    def _process_tensor(self, node: Tree) -> Tuple[str, str]:
        """Converts tensor(shape=[...], type=...) to Rust code
        
        OPTIMIZATION: Uses compact types and memory alignment
        """
        shape_node = node.children[0]
        type_node = node.children[1]
        
        # Extract dimensions
        dims = [int(child.value) for child in shape_node.children]
        total_size = dims[0]  # Only supports 1D in MVP
        
        # Maps Aureum type → Rust (OPTIMIZED for cache and memory)
        type_map = {
            # bit1.58: uses i8 to facilitate pack_ternary (will be packed into 2 bits)
            'type_bit158': ('Vec<i8>', f'Vec::with_capacity({total_size})'),
            
            # int16: uses i32 to avoid overflow in accumulations
            'type_int16':  ('Vec<i32>', f'Vec::with_capacity({total_size})'),
            
            'type_int32':  ('Vec<i32>', f'Vec::with_capacity({total_size})'),
            'type_float32': ('Vec<f32>', f'Vec::with_capacity({total_size})'),
        }
        
        rust_type, rust_init = type_map[type_node.data]
        return rust_type, rust_init
    
    def _is_bitnet_inference(self, mul_node: Tree) -> bool:
        """Checks if a multiplication is a BitNet inference (has Matryoshka operator)"""
        if not isinstance(mul_node, Tree) or mul_node.data != 'mul':
            return False
        
        # Procura por slice_expr nos filhos
        for child in mul_node.iter_subtrees():
            if child.data == 'slice_expr':
                return True
        return False
    
    def _process_bitnet_inference(self, result_var: str, mul_node: Tree):
        """
        Detects pattern: result = input * weights[::scale]
        Generates optimized call to the BitNet kernel.
        
        CRITICAL OPTIMIZATION:
        - Packs weights into 2 bits (4x memory savings)
        - Zero FP multiplications (only integer additions/subtractions)
        - Matryoshka limits processing (cycle savings)
        """
        # mul_node has: term (left) and factor (right)
        left = mul_node.children[0]   # term
        right = mul_node.children[1]  # factor
        
        # Extract input name from term->factor
        input_var = None
        if isinstance(left, Tree) and left.data == 'term':
            factor = left.children[0]
            if isinstance(factor, Tree) and factor.data == 'factor':
                input_token = factor.children[0]
                if isinstance(input_token, Token):
                    input_var = input_token.value
        
        if not input_var:
            input_var = "input"
        
        # Detect Matryoshka operator in right factor
        weights_var = None
        scale = None
        
        if isinstance(right, Tree) and right.data == 'factor':
            slice_node = right.children[0]
            if isinstance(slice_node, Tree) and slice_node.data == 'slice_expr':
                weights_token = slice_node.children[0]
                scale_token = slice_node.children[1]
                
                if isinstance(weights_token, Token):
                    weights_var = weights_token.value
                if isinstance(scale_token, Token):
                    scale = int(scale_token.value)
        
        if weights_var and scale:
            # Generate ULTRA-OPTIMIZED Rust code
            self.rust_code.append(f"")
            self.rust_code.append(f"    // ═══ BitNet b1.58 + Matryoshka OPTIMIZATION ═══")
            self.rust_code.append(f"    // Packing: {weights_var} → 2 bits/weight (4x smaller)")
            self.rust_code.append(f"    // Matryoshka scale: only {scale} elements processed")
            self.rust_code.append(f"    // Zero FP multiplications: only integer +/-")
            self.rust_code.append(f"    let packed_{weights_var} = pack_ternary(&{weights_var});")
            self.rust_code.append(f"    let {result_var} = bitnet_infer(&{input_var}, &packed_{weights_var}, {scale});")
            self.rust_code.append(f"    // ═══════════════════════════════════════════")
        else:
            # Fallback
            self.rust_code.append(f"    let {result_var} = 0; // TODO: process multiplication")

    # ─── AI-Native Standard Library visitors ──────────────────────────────

    def _process_stdlib_call(self, node: Tree) -> str:
        """Processa chamadas da stdlib nativa e retorna expressão Rust"""
        child = node.children[0]
        if not isinstance(child, Tree):
            return "/* stdlib_call inválida */"

        if child.data == 'classify_call':
            return self._gen_classify(child)
        elif child.data == 'detect_call':
            return self._gen_detect(child)
        elif child.data == 'embed_call':
            return self._gen_embed(child)
        elif child.data == 'summarize_call':
            return self._gen_summarize(child)
        elif child.data == 'similarity_call':
            return self._gen_similarity(child)
        elif child.data == 'topk_call':
            return self._gen_topk(child)
        return "/* stdlib desconhecida */"

    def _extract_slice(self, slice_node: Tree):
        """Extrai (nome_var, escala) de um slice_expr"""
        name = slice_node.children[0].value
        scale = int(slice_node.children[1].value)
        return name, scale

    def _gen_classify(self, node: Tree) -> str:
        input_var = node.children[0].value
        weights_var, scale = self._extract_slice(node.children[1])
        return (
            f"aureum_stdlib::classify(&{input_var}, &{weights_var}, "
            f"{weights_var}.len() / {input_var}.len(), {scale})"
        )

    def _gen_detect(self, node: Tree) -> str:
        seq_var = node.children[0].value
        pattern_var, scale = self._extract_slice(node.children[1])
        return f"aureum_stdlib::detect(&{seq_var}, &{pattern_var}, 0, {scale})"

    def _gen_embed(self, node: Tree) -> str:
        input_var = node.children[0].value
        proj_var, scale = self._extract_slice(node.children[1])
        return (
            f"aureum_stdlib::embed(&{input_var}, &{proj_var}, "
            f"{proj_var}.len() / {input_var}.len().max(1), {scale})"
        )

    def _gen_summarize(self, node: Tree) -> str:
        tokens_var = node.children[0].value
        attn_var, scale = self._extract_slice(node.children[1])
        return (
            f"aureum_stdlib::summarize(&{tokens_var}, {attn_var}.len(), "
            f"{tokens_var}.len() / {attn_var}.len().max(1), &{attn_var}, {scale})"
        )

    def _gen_similarity(self, node: Tree) -> str:
        a = node.children[0].value
        b = node.children[1].value
        return f"aureum_stdlib::similarity(&{a}, &{b})"

    def _gen_topk(self, node: Tree) -> str:
        scores_var = node.children[0].value
        k = int(node.children[1].value)
        return f"aureum_stdlib::topk(&{scores_var}, {k})"

    def _process_expr(self, node) -> str:
        """Converte expressão genérica para Rust"""
        if isinstance(node, Token):
            return node.value
        
        if not hasattr(node, 'data'):
            return str(node)
        
        # Processa diferentes tipos de nós
        if node.data == 'factor':
            # Factor pode conter NAME, NUMBER, stdlib_call ou outra expressão
            if len(node.children) > 0:
                child = node.children[0]
                if isinstance(child, Tree) and child.data == 'stdlib_call':
                    return self._process_stdlib_call(child)
                return self._process_expr(child)
            return "0"
        
        elif node.data == 'term':
            # Term pode conter factor ou operações
            if len(node.children) > 0:
                return self._process_expr(node.children[0])
            return "0"
        
        elif node.data == 'expr':
            # Expr pode conter term ou operações
            if len(node.children) > 0:
                return self._process_expr(node.children[0])
            return "0"
        
        elif node.data == 'add':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left} + {right})"
        
        elif node.data == 'sub':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left} - {right})"
        
        elif node.data == 'mul':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left} * {right})"
        
        elif node.data == 'div':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left} / {right})"
        
        elif node.data == 'mod':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left} % {right})"
        
        elif node.data == 'pow':
            left = self._process_expr(node.children[0])
            right = self._process_expr(node.children[1])
            return f"({left}.pow({right}))"
        
        elif len(node.children) > 0 and isinstance(node.children[0], Token):
            return node.children[0].value
        
        return "0"


def main():
    """Transpiler CLI"""
    if len(sys.argv) < 2:
        print("Usage: python compiler.py <file.aur>")
        sys.exit(1)
    
    source_file = Path(sys.argv[1])
    if not source_file.exists():
        print(f"Error: file '{source_file}' not found")
        sys.exit(1)
    
    # Locate grammar
    grammar_path = Path(__file__).parent / "grammar.lark"
    
    # Compile
    transpiler = AureumTranspiler(str(grammar_path))
    source_code = source_file.read_text(encoding='utf-8')
    
    try:
        rust_code = transpiler.compile(source_code)
        
        # Save generated Rust code
        output_file = source_file.with_suffix('.rs')
        output_file.write_text(rust_code, encoding='utf-8')
        
        print(f"✓ Transpilation complete: {output_file}")
        print("\n" + "="*70)
        print(rust_code)
        print("="*70)
        
    except Exception as e:
        print(f"Transpilation error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
